---
- name: Provisioning Software
  hosts: all
  become: yes
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      tags: nginx

    - name: Enable Nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started
      tags: nginx


    