---
- name: Provisioning Software
  hosts: all
  become: yes
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      tags: nginx

    - name: Enable Nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started
      tags: nginx

    - name: Allow incoming traffic on ports 22, 80, and 443
      ufw:
        rule: allow
        port: "{{ item }}"
      with_items:
        - 22
        - 80
        - 443
      tags: ufw

    - name: Enable UFW (Uncomplicated Firewall)
      command: ufw enable
      stdin: 'y'
      tags: ufw

    
