---
- name: Install IIS on Windows
  hosts: windows
  tasks:
    - name: Install Web-Server (IIS) feature
      win_feature:
        name: Web-Server
        state: present
      register: iis_installed

    - name: Verify IIS installation
      debug:
        msg: "Web-Server (IIS) is installed"
      when: iis_installed.changed

    - name: Ensure IIS service is running
      win_service:
        name: W3SVC
        start_mode: auto
        state: started
