
name: Terraform-Azure

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "feature/hcp-terraform-azure-linux" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:

env:
  HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
  HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
  HCP_ORGANIZATION_ID: ${{ secrets.HCP_ORGANIZATION_ID }}
  HCP_BUCKET_NAME: "packer-azure"
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: development
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    # Checkout the repository to the GitHub Actions runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      #- name: Setup Terraform
      #  uses: hashicorp/setup-terraform@v1
        
      #- name: Set up Azure CLI
      #  run: |
      #    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      #    az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      #    az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #    az --version
      #    az account show
      
      #- name: Set up Azure CLI
      #  uses: azure/login@v1
      #  with:
      #    creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7        
      
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=true   

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=true

      
      
